### ISSUE TITLE
Hawk breaks controller

### ISSUE THREAD

**Issue by ErmineII** [jthistle/KOTH-counting#2]
[My answer using Hy](https://codegolf.stackexchange.com/a/223241/90614) causes a syntax error when running `arena.py`. What should I do to change my answer so it doesn't fail, or can you change the query to successfully find the python (a worse solution because older clones still won't work)?

**Comment by jthistle** [comment]
Hi! As I commented on your post a moment ago, you just need to put the Python code above the Hy in your answer. Thanks!

**Comment by jthistle** [comment]
Closing as fixed
